### ISSUE TITLE
Model fit failure

### ISSUE THREAD

**Issue by Gregory-Humble** [fooof-tools/fooof#168] opened 2020-04-11 07:31 UTC
Hello there,
I'm unable to get a model to fit to an of my data (about 200 datasets) and I've been unsuccessful in my troubleshooting. I'm not sure as to why this is the case. 
Here is an example of the output I get from a single dataset:

                                   FOOOF - POWER SPECTRUM MODEL                                   
                                                                                                  
                        The model was run on the frequency range 3 - 45 Hz                        
                                 Frequency Resolution is 1.00 Hz                                  
                                                                                                  
                            Aperiodic Parameters (offset, exponent):                              
                                          0.8320, 1.4975                                          
                                                                                                  
                                       3 peaks were found:                                        
                                CF:   9.42, PW:  0.705, BW:  5.10                                 
                                CF:  16.86, PW:  0.204, BW:  5.27                                 
                                CF:  35.45, PW:  0.161, BW:  3.53                                 
                                                                                                  
                                     Goodness of fit metrics:                                     
                                    R^2 of model fit is 0.9920                                    
                                    Error of the fit is 0.0404                                    
                                                                                                  
==================================================================================================
<fooof.objs.fit.FOOOF object at 0x000001F6AFAC1588>
Goodness of fit:
 Error -  nan
 R^2   -  nan 

Could you please advise as to what might be going wrong with the model fitting of my data?

Any advice would be much appreciated.

Regards,
Greg

**Comment by TomDonoghue** [comment] 2020-04-11 16:58
Hey Greg, 
I'm not quite sure I understand the problem - that report print out you added reflects a model fit, so I don't think I'm seeing where the problem is. The nan's below it for the goodness-of-fit metrics might relate to a problem, but I'm unclear on where those are from. 

Are you getting a `FitError` or a `NoModelError` somewhere? Could you maybe say more about what you mean by not being able to fit a model, and/or post a code snippet that is failing?

**Comment by Gregory-Humble** [comment] 2020-04-12 07:09
Hi Tom,

Thanks for the quick response! Sorry, you are right that the model is being fit, but when I try to save/output the values of of the model fit as a .json file none of the model fit values are saved/exported. 

Here is my code that i'm using to fit the models and export the data:

```
ID = ['P301']

for participant in ID:
    #print(ID)
    myPath = 'E:\\One_Over_F\\fooof\\RSEEG_BL\\'
    idnum = participant
    fn = 'PowerSpectra.mat'
    partdata = myPath + idnum + fn
    print(partdata)
    # Load the mat file 
    dat = loadmat(partdata)
    # Unpack data from dictionary, and squeeze into numpy arrays
    freqs = np.squeeze(dat['freqs']).astype('float')
    psds = np.squeeze(dat['psds']).astype('float')
    
    # Transpose power spectra, to have the expected orientation for FOOOF
    psds = psds.T  
    # Set whether to plot in log-log space (used across the whole notebook)
    plt_log = False
    
    EOI = [5,9,30,34]
    for ind in EOI:
        print('channel no:')
        print(ind)
        EOIspectrum = psds[ind, :]
        print(EOIspectrum)
        fm = FOOOF(peak_width_limits=[1, 8], max_n_peaks=6 , min_peak_amplitude=0.15)
        # Define frequency range across which to model the spectrum
        freq_range = [1, 50]
        # Model the power spectrum with FOOOF, and print out a report
        fm.report(freqs, EOIspectrum, freq_range)
        print(fm)
        
        # Add data to FOOOF object
        fm.add_data(freqs, EOIspectrum, [1, 50])
        # Plot the power spectrum that we just added
        fm.plot(plt_log)

        # Goodness of fit measures
        print('Goodness of fit:')
        print(' Error - ', fm.error_)
        print(' R^2   - ', fm.r_squared_, '\n')
        
        # output and save data 
        fm.save(file_name = 'fooof_EOI_results' + '_' + idnum + '_' +str(ind), save_results = True)
        myPath = 'E:\\One_Over_F\\fooof_output\\'
        fm.save_report(str(myPath) + 'fooof_EOIreport' + '_' + idnum + '_' +str(ind), myPath, plt_log)
```

And here is an example of the report that is generated following running the script on a single subject:
==================================================================================================
                                                                                                  
                                   FOOOF - POWER SPECTRUM MODEL                                   
                                                                                                  
                        The model was run on the frequency range 1 - 45 Hz                        
                                 Frequency Resolution is 1.00 Hz                                  
                                                                                                  
                             Background Parameters (offset, slope):                               
                                          1.6338, 1.6113                                          
                                                                                                  
                                       5 peaks were found:                                        
                                CF:   6.29, Amp:  0.179, BW:  1.00                                
                                CF:   9.76, Amp:  0.252, BW:  2.27                                
                                CF:  16.06, Amp:  0.367, BW:  4.22                                
                                CF:  26.47, Amp:  0.147, BW:  5.08                                
                                CF:  32.03, Amp:  0.149, BW:  2.31                                
                                                                                                  
                                     Goodness of fit metrics:                                     
                                    R^2 of model fit is 0.9984                                    
                                Root mean squared error is 0.0203                                 
                                                                                                  
==================================================================================================
<fooof.fit.FOOOF object at 0x00000185D1909108>
Background parameters: 
 [nan nan] 

Peak parameters: 
 [nan nan nan] 

Goodness of fit:
 Error -  nan
 R^2   -  nan 


Again, any advice you could offer me as to what might be going on would be much appreciated.

Regards,
Greg

**Comment by TomDonoghue** [comment] 2020-04-12 19:40
Ah, okay I see the issue! It's just a little code-usage thing. 

Quick answer - just remove the extra add data line you have in your code:
```
  # Add data to FOOOF object
fm.add_data(freqs, EOIspectrum, [1, 50])
```

Why? The `report` call adds the data to the object, and then fits the model. The data and model data are now in the object, and you see them printed. However, when you do the next `add_data` call, it clears out the previous data and model results (to make sure the object stays consistent - otherwise it could end up with a mismatch in model and data). That's why the result fields are empty when you access them later - they we're cleared in the `add_data` line. 

After doing `report` you can call `fm.plot(plt_log)` to re-plot the data (it's already in the object at that point), without having to re-add data.

**Comment by Gregory-Humble** [comment] 2020-04-13 03:15
Hi Tom,

Thanks so much for your assistance and clarifications! It works.

Very much appreciated!

All the best,
Greg

**Comment by TomDonoghue** [comment] 2020-04-13 03:22
Awesome, glad to hear! Since this is resolved, I'm going to close this issue, but feel free to ask any more questions if anything comes up!

**Closed by TomDonoghue** 2020-04-13 03:22 UTC
