### ISSUE TITLE
FOOOF fails uninformatively if it doesn't have enough points to estimate. 

### ISSUE THREAD

**Issue by tyfarnan** [fooof-tools/fooof#138] opened 2019-03-16 01:19 UTC
Code example that fails (sometimes - but not deterministically):
```
from neurodsp import sim
from fooof import FOOOFGroup
from scipy.signal import spectrogram

s_rate = 1000
sig = sim.sim_variable_powerlaw(20, s_rate, -1)
fsg, ts, pss = spectrogram(sig, s_rate, window='hann', nperseg=250, noverlap=500/8)
fg = FOOOFGroup(peak_width_limits=(1, 6), verbose=False)
fg.fit(fsg, pss.T, [1, 30])
```

Note: looks to be an interaction with the sub-sampling in the aperiodic fit, that can lead to selecting not enough points (given the data), when the power spectrum (over the given range) does not have a lot of points). 

Filed with @TomDonoghue

**Comment by TomDonoghue** [comment] 2019-12-11 01:22
Oops - ended up with a duplicate of this, which is the same as #153. 

Closing this one.

**Closed by TomDonoghue** 2019-12-11 01:22 UTC
Labels: duplicate
